# Generated by Django 4.2.13 on 2024-05-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='group_max_size',
            new_name='participants_max',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='group_min_size',
            new_name='participants_min',
        ),
    ]
