# Generated by Django 4.2.13 on 2024-05-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0002_rename_group_max_size_timeslot_participants_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varkal.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varkal.user')),
            ],
        ),
    ]
