# Generated by Django 4.2.13 on 2024-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0003_user_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
