# Generated by Django 4.2.13 on 2024-05-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0004_reservation_cancelled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='activity',
            new_name='service',
        ),
    ]
