# Generated by Django 4.2.13 on 2024-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0006_alter_reservation_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
