# Generated by Django 4.2.13 on 2024-06-07 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0007_alter_place_info_alter_service_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=45, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='participants_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='participants_min',
            field=models.PositiveIntegerField(),
        ),
    ]
