# Generated by Django 4.2.13 on 2024-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0008_service_duration_alter_timeslot_participants_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
