# Generated by Django 4.2.13 on 2024-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0009_timeslot_participants'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(check=models.Q(('participants__lte', models.F('participants_max'))), name='check_participants'),
        ),
    ]
