# Generated by Django 4.2.13 on 2024-06-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0010_timeslot_check_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default='your@email.here', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='First name', max_length=120),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Last name', max_length=120),
        ),
    ]
