# Generated by Django 4.2.13 on 2024-07-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0013_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='varkal.service'),
        ),
    ]
