# Generated by Django 4.2.13 on 2024-07-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0014_alter_timeslot_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varkal.service'),
        ),
    ]
