# Generated by Django 4.2.13 on 2024-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0016_customer_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
