# Generated by Django 4.2.13 on 2024-09-23 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varkal', '0017_reservation_cancel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cancel_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
